name: seotbx
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - pip
  - numpy
  - scipy
  - gdal
  - seaborn
  - matplotlib
  - geopandas
  - geoplot
  - owslib
  - pip:
    - -r requirements.txt
