name: seotbx
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - pip
  - numpy
  - scipy
  - gitdb
  - gitpython
  - h5py
  - hdf5plugin
  - opencv
  - gdal
  - seaborn
  - matplotlib
  - geopandas
  - geoplot
  - owslib
  - umap-learn
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - boost
  - pip:
    - -r requirements.txt
    - git+https://github.com/PyTorchLightning/pytorch-lightning
